### ISSUE TITLE
Add support for accessing reflection Field info outside of Decoder?

### ISSUE THREAD

**Issue by ashb** [VinGarcia/structscanner#3]
Hello I found this module and it makes what I'm trying to do a lot easier.

One ask I have is if we could "cache" the reflect parsing ahead of time instead of need to re-compute it each time we try to decode a struct -- the reason I'd like this is that I'm using this decoder in my http handler (built on top of Gin) and the decoder/parsing doesn't change from type to type, but having to re-reflect each and every request is a bit wasteful.

I'm more than happy to open a PR to this if you are happy with this?

My rough idea is to turn this

```go
func Decode(targetStruct interface{}, decoder TagDecoder) error {
	t, v, fields, err := getStructInfo(targetStruct)
	if err != nil {
		return err
	}
	...
}
```

Into this:

```go
func Decode(targetStruct interface{}, tagDecoder TagDecoder) error {
	structDecoder, err := NewDecoder(targetStruct, tagDecoder)
	if err != nil {
		return err
	}
	err = structDecoder.Decode(targetStruct)
	if err != nil {
		return err
	}
}
type StructDecoder struct {
	Type reflect.Type
	Fields []Field
}	

func NewDecoder(targetStruct interface{}, tagDecoder TagDecoder), (s StructDecoder, err error){
	s.Type, _, s.Fields, err := getStructInfo(targetStruct)
}

func (s StructDecoder) Decode(targetStruct interface{}) error {
	t = s.Type
	fields = s.Fields
	v  := reflect.ValueOf(targetStruct)
	// Rest of existing code
	...
}
```

Names could probably do some work, but something like this.

Thoughts?

**Comment by VinGarcia** [comment]
Hello @ashb, sorry for the delay to answer, yeah this might be a good thing indeed, I had a similar problem actually when I was thinking about using this library on a similar situation (wrapping an http library on the server side).

Ok so some things to keep in mind before I go too much into this:

The first thing is that we should probably have a benchmark, odds are this might not really cause any impact on performance since the operations to read the type and etc might not be the actual bottleneck.

Check [This Benchmark](https://github.com/VinGarcia/go-reflection-benchmark?tab=readme-ov-file#results) I wrote, with focus on these two values:

- `toMapWithNoReflection` taking 523
- `toMapUsingCachedTagNames` taking 607

The first one is literally using zero reflection, and the second one is more or less what we are doing here. The difference is small 523 vs 607 (i.e. only 16% slower with reflection), and with bigger data types this tends to become even less significant. So for example if this new solution adds a single operation of full-copy of the struct this might be enough the make it as performant as what we currently have. (I can write this benchmark for us I think)

Also on the same benchmark above you will see what actually gives reflection a bad reputation, take a look at the benchmark labeled: `toMapUsingTag`. In this one we parse the tags from the struct every time, and this makes it extremely slower. In our current implementation this is being cached already.

The second thing to keep in mind is that even though this library is very small at the moment (since I am not promoting it yet), I would like to try to think of the best interface we can give to the user. So I will need to brain storm a little about it.

---

Finally about your current proposal, as an API for the library this might be unsafe in the sense that a library should never panic unless if it is an actual code error. And being able to pass a different struct on the call to `Decode()` would probably cause a panic unless we added at least one more type check e.g.:

```golang
func (s StructDecoder) Decode(targetStruct interface{}) error {
	t = s.Type
	fields = s.Fields
	v  := reflect.ValueOf(targetStruct)
	if v.Type() != s.OriginalType {
		return fmt.Errorf("types must match ...", ...)
	}
```

So the implementation would look something like this:

```golang
func Decode(targetStruct interface{}, tagDecoder TagDecoder) error {
	structDecoder, err := NewDecoder(targetStruct, tagDecoder)
	if err != nil {
		return err
	}
	err = structDecoder.Decode(targetStruct, tagDecoder)
	if err != nil {
		return err
	}
}

type StructDecoder struct {
	targetStruct interface{}
	originalType reflect.Type
	type reflect.Type
	fields []Field
}	

func NewDecoder(targetStruct interface{}, tagDecoder TagDecoder), (s StructDecoder, err error){
	s.targetStruct = targetStruct
	
	// Here I added an extra return value with the original type:
	s.originalType, s.type, _, s.fields, err := getStructInfo(targetStruct)

	return s, err // I prefer to always use explicit returns
}

func (s StructDecoder) Decode(targetStruct interface{}) error {
	t = s.type
	fields = s.fields
	v  := reflect.ValueOf(targetStruct)
	if v.Type() != s.OriginalType {
		return fmt.Errorf("struct decoder expected an instance of %v but got %v", s.OriginalType, v.Type())
	}

	// Rest of existing code
	...
}
```

That said I am still thinking if we can come up with a better API, right now the usage of this flow would look like this:

```golang
type Request struct{
    // ... some attrs ...
}

func someWorker(inputCh chan Args, outCh chan Request) {
	structDecoder, err := structscanner.NewDecoder(&Request{})
	if err != nil {
		return err
	}

	for _, dataSource := range inputCh {
		var req Request
		err = structDecoder.Decode(&req, NewMyTagDecoder(dataSource))
		if err != nil {
			return err
		}
		outCh <- req
	}
}
```

I think it is actually a nice solution. It is not too complicated, and I don't foresee any future issues 🤔 

I think you can go for it. I will try to write the benchmark for the current version today, so when we have your PR we can compare the implementations, if it is at least slightly faster we should keep it.

**Comment by ashb** [comment]
Sounds good!

Another thought as a way to avoid panic might be to use generics - that way passing the wrong struct type to Decode becomes a compile error

One other thing I would find useful is the ability to access the Fields[] outside of decoding a struct as part of OpenAPI spec generation

**Comment by VinGarcia** [comment]
Hmmm, @ashb actually it occurred to me a solution that might do the exact same number of operations but keeping the current API, maybe we can just improve the caching system to do less operations before using the cache, because currently this is what we have:

```golang
func getStructInfo(targetStruct interface{}) (reflect.Type, reflect.Value, []Field, error) {
	v := reflect.ValueOf(targetStruct)
	t := v.Type()
	if t.Kind() != reflect.Ptr {
		return nil, reflect.Value{}, nil, fmt.Errorf("expected struct pointer but got: %T", targetStruct)
	}
	if v.IsNil() {
		return nil, reflect.Value{}, nil, fmt.Errorf("expected non-nil pointer to struct, but got: %#v", targetStruct)
	}

	t = t.Elem()

	if t.Kind() != reflect.Struct {
		return nil, reflect.Value{}, nil, fmt.Errorf("can only get struct info from structs, but got: %#v", targetStruct)
	}

	data, _ := structInfoCache.Load(t)
	info, ok := data.([]Field)
	if ok {
		return t, v, info, nil
	}

	// ...

	structInfoCache.Store(t, info)
	return t, v, info, nil
}
```

But what if instead we used the original type as key on the cache, this would allow us to skip several operations, e.g.:

```
func getStructInfo(targetStruct interface{}) (reflect.Type, reflect.Value, []Field, error) {
	v := reflect.ValueOf(targetStruct)
	originalType := v.Type()

	data, _ := structInfoCache.Load(originalType)
	info, ok := data.([]Field)
	if ok {
		return info.Type, v, info.Fields, nil
	}

	if originalType.Kind() != reflect.Ptr {
		return nil, reflect.Value{}, nil, fmt.Errorf("expected struct pointer but got: %T", targetStruct)
	}
	if v.IsNil() {
		return nil, reflect.Value{}, nil, fmt.Errorf("expected non-nil pointer to struct, but got: %#v", targetStruct)
	}

	t := originalType.Elem()

	if t.Kind() != reflect.Struct {
		return nil, reflect.Value{}, nil, fmt.Errorf("can only get struct info from structs, but got: %#v", targetStruct)
	}

	// ...

	structInfoCache.Store(originalType, info)
	return t, v, info, nil
}
```

This would mean that before we started doing the operations we would only perform one call to `reflect.ValueOf` and another to `v.Type()` which we would necessarily also have to make on your implementation, what do you think about this simpler approach, is there something I am missing?

**Comment by ashb** [comment]
That night work too yes, and my other ask could be met by making that function exported

**Comment by VinGarcia** [comment]
Would it really be necessary to export it? 🤔 

I think that with this optimization having just using the existing `structdecoder.Decode()` function would be exactly as efficient for handling several different structs as it is in the proposal above for the same struct.

Like the best of both worlds: We could keep the API as simple as possible (a single public Decode function) while also having the best performance possible.

**Comment by ashb** [comment]
Export wouldn't be needed for this, no, but I'd like to reuse this information in other ways

**Comment by VinGarcia** [comment]
> Sounds good!
> 
> Another thought as a way to avoid panic might be to use generics - that way passing the wrong struct type to Decode becomes a compile error
> 
> One other thing I would find useful is the ability to access the Fields[] outside of decoding a struct as part of OpenAPI spec generation

Oh sorry I missed this message.

Yeah, indeed using generics here might work for that. But then we would have to make the benchmark to be sure this optimization is really improving performance since generics docs do mention some performance loss.

About your last comment, yeah you want to have this information about the fields outside.

I think it's a good idea too, we just need to make sure we return a struct so it's easier to add more fields as necessary in the future.

**Comment by VinGarcia** [comment]
Finally now you mentioned Open API I think you might be thinking about implementing something I am also thinking about.

Are you thinking about implementing an http server framework that supports structs as inputs and outputs in order to (among other things) build a swagger doc automatically?

**Comment by VinGarcia** [comment]
Hey @ashb, I really liked both your suggestions, do you want to implement them? If you do, I will leave it to you so you can add your name to the project, otherwise I can implement them myself too.

And again thanks for opening this issue =].

**Comment by ashb** [comment]
> Are you thinking about implementing an http server framework that supports structs as inputs and outputs in order to (among other things) build a swagger doc automatically?

Yes, exactly. I am initially building it on top of Gin as that's what we use at my work. I've got 90% of a poc already written. I'll get the sign off to open source it then I'd be happy to collaborate on it
